name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Set up Node.js (adjust version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'
      
      # Install Node dependencies here
      - name: Install dependencies
        run: npm install
      
      # Running the unit tests
      - name: Run tests
        run: npm test
      
      # Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "dash-production-app"
          heroku_email: "ypatel341@gmail.com"
