name: Deploy

on:
  push:
    branches:
      - main
      - dockerization

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      # Step 2: Checkout code from the repository
      - uses: actions/checkout@v2

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install --omit=dev

      # Step 5: Build the frontend and backend
      - name: Build frontend
        run: npm run build-frontend

      - name: Build backend
        run: npm run build-backend

      # Step 6: Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: 'main'
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          clean: true
          copy: "dist build package.json package-lock.json" # Deploy only necessary files

      # Step 7: Start the application
      - name: Start application
        run: npm run start-all-prod