name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version
          apt-get install nodejs-legacy

      # Step 2: Checkout code from the repository
      - uses: actions/checkout@v2

      # Step 3: Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: "main"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
